package:
  name: cosmicmuffin
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"
source:
  path: ../../
build:
  number: 1
requirements:
  build:
  - python
  - pip
  - setuptools >=61.0
  - versioningit~=2.0
  run:
  - python
  - pip
  - setuptools >=61.0
  - versioningit~=2.0
about:
  home: https://uibcdf.org
  license: MIT License
  summary: ''
  description: 'This is a test library

    '
  dev_url: https://github.com/uibcdf/CosmicMuffin
  doc_url: https://uibcdf.org/CosmicMuffin
